### ISSUE TITLE
new release for "epic-parser-en-span"

### ISSUE THREAD

**Issue by jiangss** [dlwh/epic#23]
Hi, David,

May I ask whether you have a latest release for "epic-parser-en-span" after "2014.9.15"? If not, would you please make one for both Scala 2.10 and 2.11?

Thanks!

**Comment by dlwh** [comment]
Making a new one today.

**Comment by jiangss** [comment]
Hi David,

Thanks for the new release Epic v3.0. May I ask what is the version for the Epic parser model "epic-parser-en-span"? Thank you.

**Comment by dlwh** [comment]
sorry. it's still building. Should be done by tonight.

**Comment by jiangss** [comment]
Cool. Thanks!

**Comment by dlwh** [comment]
ok, new release. depends on epic 0.3, and has version number 2015.1.25

**Comment by jiangss** [comment]
Thanks David!
