### ISSUE TITLE
Development environment

### ISSUE THREAD

**Issue by woj-i** [dlwh/epic#34]
Hi!
I try to setup the project in a Intellij 14 IDE with a Scala plugin and sbt 0.13.7
I can see a lot of errors posted by IntelliJ in build.sbt as well as in classes. However, the project compiles well, I can run sbt assembly and get a jar.

Please, write in Wiki your development environment IDE+additional tools and versions to be able to load the project without errors.

**Comment by pommedeterresautee** [comment]
No errors for me with same config. May be on your side?

**Comment by dlwh** [comment]
IntelliJ just gets confused by Breeze code. There's going to be lots of red squiggles that compiles fine.

**Comment by reactormonk** [comment]
I've looked through a few files with ensime, seems to work fine.
