### ISSUE TITLE
Directional quotes going the wrong way for UTF close-double-quote?

### ISSUE THREAD

**Issue by mrjf** [dlwh/epic#41]
https://github.com/dlwh/epic/blob/master/src/main/scala/epic/preprocess/TreebankTokenizer.scala#L52

```
      case "“" => inOpenQuote = true; output += "``"
      ...
      case "”" => inOpenQuote = false; output += "``"
```

Should that be a ```+="''"``` for the curly close quote?

Thanks for Epic!

**Comment by mrjf** [comment]
And same for single quote?

https://github.com/dlwh/epic/blob/master/src/main/scala/epic/preprocess/TreebankTokenizer.scala#L50

**Comment by dlwh** [comment]
thanks!
