### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by freeze5272** [dlwh/epic#42]
Hi, there are two errors occurred when I tried to build epic.
<img width="682" alt="2015-09-29 12 53 02" src="https://cloud.githubusercontent.com/assets/13763133/10162157/8759e45c-66a9-11e5-93f7-b1a9aad76309.png">
Is there any possible way that I can fix it?

**Comment by reactormonk** [comment]
Could you post it as string instead of image? For copy/pasting.

**Comment by freeze5272** [comment]
[error] /Users/edward/Downloads/epic-master-2/target/scala-2.11/src_managed/main/TreebankTokenizerImpl.java:7327: unclosed character literal

[error]     return currentToken(new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead).replace('???', '\'').replace('??','\u0308').replaceAll("-[\n\r]+",""));

[error]                                                                                             ^

[error] /Users/edward/Downloads/epic-master-2/target/scala-2.11/src_managed/main/TreebankTokenizerImpl.java:7327: unclosed character literal

[error]     return currentToken(new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead).replace('???', '\'').replace('??','\u0308').replaceAll("-[\n\r]+",""));

[error]                                                                                                 ^

[error] two errors found

[error] (compile:compileIncremental) Compilation failed

**Comment by dlwh** [comment]
the file encoding for compiling the java code is wrong. It's a UTF-8 file,
and I guess that needs to be set. You could either change your terminal's
default encoding, or do something like

javacOptions ++= Seq("-encoding", "UTF-8")

in build.sbt

-- David
