### ISSUE TITLE
Can't build - module not found: org.scalanlp#breeze_2.10;0.12-SNAPSHOT

### ISSUE THREAD

**Issue by subhagsingh** [dlwh/epic#48]
Hi, I tried to build using different versions of Scala and sbt both, but no luck. Please help.
![screen shot 2016-02-15 at 2 41 15 am](https://cloud.githubusercontent.com/assets/11255597/13048191/142743d2-d399-11e5-8421-669287e3a80e.jpg)

**Comment by dlwh** [comment]
sorry about that, delete the -SNAPSHOT part from build.sbt (just do 0.12)

**Comment by subhagsingh** [comment]
Great! It worked! Thanks a lot David!
