### ISSUE TITLE
org.scalanlp#breeze_2.11;0.12-SNAPSHOT: not found

### ISSUE THREAD

**Issue by cj2001** [dlwh/epic#49]
I just cloned Epic and went to try and run "sbt assembly" and got the following error message:

[error] (*:update) sbt.ResolveException: unresolved dependency: org.scalanlp#breeze_2.11;0.12-SNAPSHOT: not found

So I went ahead and installed Breeze just fine and reran in the Epic install, but still got the same error.  Suggetions?

**Comment by dlwh** [comment]
Sorry for the slow response. It's fixed in master
